### ISSUE TITLE
compare condition not working right

### ISSUE THREAD

**Issue by colorant** [alibaba/wasp#10]
" > acting as >= "
" and <= acting as <"

As following:

wasp(main):044:0> query "select \* from Photo where user_id>3"
+----------+-----------+-----------+-----------+----------------+-------+
| user_id  | photo_id  |   time    | full_url  | thumbnail_url  |  tag  |
+----------+-----------+-----------+-----------+----------------+-------+
| 5        | 501       | 20130728  | fullurl2  | thumburl2      | tag2  |
| 6        | 601       | 20130728  | fullurl2  | thumburl2      | tag2  |
+----------+-----------+-----------+-----------+----------------+-------+

wasp(main):045:0> query "select \* from Photo where user_id<=6"
+----------+-----------+-----------+-----------+----------------+-------+
| user_id  | photo_id  |   time    | full_url  | thumbnail_url  |  tag  |
+----------+-----------+-----------+-----------+----------------+-------+
| 5        | 501       | 20130728  | fullurl2  | thumburl2      | tag2  |
+----------+-----------+-----------+-----------+----------------+-------+

wasp(main):046:0> query "select \* from Photo where user_id>5"
+----------+-----------+-----------+-----------+----------------+-------+
| user_id  | photo_id  |   time    | full_url  | thumbnail_url  |  tag  |
+----------+-----------+-----------+-----------+----------------+-------+
| 5        | 501       | 20130728  | fullurl2  | thumburl2      | tag2  |
| 6        | 601       | 20130728  | fullurl2  | thumburl2      | tag2  |
+----------+-----------+-----------+-----------+----------------+-------+

**Comment by jaywong85** [comment]
thx for reporting. I have fix the bug  already push the code .:)
