### ISSUE TITLE
Question about the design

### ISSUE THREAD

**Issue by colorant** [alibaba/wasp#12]
Just curious, where is the code in wasp which related to cross cluster/data center design in megastore paper. Seems to me wasp don't handle this part and all data is reside in one HBase cluster and no replica other than HDFS replica is done?

And if this is true, does this mean that wasp only target at cross row transaction and SQL interface? other part of Megastore design is not included?

**Comment by colorant** [comment]
Btw. Does the SQL support not ready yet? according to 海量数据分布式数据库的探索:WASP, there will be some join/group by/sum support etc. While I don't see it in the code, or I miss them?

How do you plan to implement them? especially those aggregation involved features? would you use HBase CP hook or done with FServer on EntityGroup level or purely at Client side?

**Comment by jaywong85** [comment]
count sum avg will be implement in the next version.

other part of Megastore design is not included? U mean what?

**Comment by colorant** [comment]
cross cluster replica of the EntityGroup, and read from nearest local server. and various other fail safe approachings. Say the components that make megastore really mega.

**Comment by jaywong85** [comment]
1. not cross datacenter. no multi replica
2. as wasp not have multi clusters. so read from the target entityGroup first.
3. wasp does not have witnesses.
   maybe not reall mega :)  
   try our best together
