### ISSUE TITLE
创建索引失败

### ISSUE THREAD

**Issue by ihadoop** [alibaba/wasp#14]
13/08/05 11:20:46 INFO jdbc.JdbcConnection: Connection conn = DriverManager.getConnection("jdbc:wasp:", "", "");
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.5-1392090, built on 09/30/2012 17:52 GMT
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:host.name=cstor
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:java.version=1.7.0_02
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:java.home=C:\Program Files\Java\jre7
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:java.class.path=C:\Users\cstor\workspace\wasp-test\bin;C:\Users\cstor\workspace\wasp-test\lib\activation-1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\aopalliance-1.0.jar;C:\Users\cstor\workspace\wasp-test\lib\asm-3.1.jar;C:\Users\cstor\workspace\wasp-test\lib\avro-1.5.3.jar;C:\Users\cstor\workspace\wasp-test\lib\avro-ipc-1.5.3.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-beanutils-1.7.0.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-beanutils-core-1.8.0.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-cli-1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-codec-1.7.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-collections-3.2.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-configuration-1.6.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-digester-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-el-1.0.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-httpclient-3.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-io-2.4.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-lang-2.6.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-logging-1.1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-math-2.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-net-1.4.1.jar;C:\Users\cstor\workspace\wasp-test\lib\core-3.1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\druid-0.2.9.jar;C:\Users\cstor\workspace\wasp-test\lib\ftplet-api-1.0.0.jar;C:\Users\cstor\workspace\wasp-test\lib\ftpserver-core-1.0.0.jar;C:\Users\cstor\workspace\wasp-test\lib\ftpserver-deprecated-1.0.0-M2.jar;C:\Users\cstor\workspace\wasp-test\lib\guava-12.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\hadoop-core-1.0.3.jar;C:\Users\cstor\workspace\wasp-test\lib\hadoop-test-1.0.3.jar;C:\Users\cstor\workspace\wasp-test\lib\hamcrest-core-1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\hbase-0.94.1-tests.jar;C:\Users\cstor\workspace\wasp-test\lib\hbase-0.94.1.jar;C:\Users\cstor\workspace\wasp-test\lib\high-scale-lib-1.1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\hsqldb-1.8.0.10.jar;C:\Users\cstor\workspace\wasp-test\lib\htrace-1.49.jar;C:\Users\cstor\workspace\wasp-test\lib\httpclient-4.1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\httpcore-4.1.3.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-core-asl-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-jaxrs-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-mapper-asl-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-xc-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jamon-runtime-2.3.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jasper-compiler-5.5.23.jar;C:\Users\cstor\workspace\wasp-test\lib\jasper-runtime-5.5.23.jar;C:\Users\cstor\workspace\wasp-test\lib\jaxb-api-2.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jaxb-impl-2.2.3-1.jar;C:\Users\cstor\workspace\wasp-test\lib\jersey-core-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jersey-json-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jersey-server-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jets3t-0.7.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jettison-1.3.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jetty-6.1.26.jar;C:\Users\cstor\workspace\wasp-test\lib\jetty-util-6.1.26.jar;C:\Users\cstor\workspace\wasp-test\lib\jruby-complete-1.6.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jsp-2.1-6.1.14.jar;C:\Users\cstor\workspace\wasp-test\lib\jsp-api-2.1-6.1.14.jar;C:\Users\cstor\workspace\wasp-test\lib\jsr305-1.3.9.jar;C:\Users\cstor\workspace\wasp-test\lib\junit-4.10.jar;C:\Users\cstor\workspace\wasp-test\lib\kfs-0.3.jar;C:\Users\cstor\workspace\wasp-test\lib\libthrift-0.8.0.jar;C:\Users\cstor\workspace\wasp-test\lib\log4j-1.2.17.jar;C:\Users\cstor\workspace\wasp-test\lib\metrics-core-2.1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\mina-core-2.0.0-M5.jar;C:\Users\cstor\workspace\wasp-test\lib\mockito-all-1.9.0.jar;C:\Users\cstor\workspace\wasp-test\lib\netty-3.2.4.Final.jar;C:\Users\cstor\workspace\wasp-test\lib\netty-3.5.0.Final.jar;C:\Users\cstor\workspace\wasp-test\lib\oro-2.0.8.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-java-2.4.1.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-java-format-1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-rpc-pro-demo-2.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-rpc-pro-duplex-2.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-streamer-pro-1.2.3.jar;C:\Users\cstor\workspace\wasp-test\lib\servlet-api-2.5-6.1.14.jar;C:\Users\cstor\workspace\wasp-test\lib\slf4j-api-1.4.3.jar;C:\Users\cstor\workspace\wasp-test\lib\slf4j-log4j12-1.4.3.jar;C:\Users\cstor\workspace\wasp-test\lib\snappy-java-1.0.3.2.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-aop-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-asm-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-beans-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-context-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-core-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-expression-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\stax-api-1.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\velocity-1.7.jar;C:\Users\cstor\workspace\wasp-test\lib\wasp-0.10.jar;C:\Users\cstor\workspace\wasp-test\lib\xmlenc-0.52.jar;C:\Users\cstor\workspace\wasp-test\lib\zookeeper-3.4.5.jar
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:java.library.path=C:\Program Files\Java\jre7\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\MinGW\bin;C:\Program Files (x86)\Git\bin;C:\tools\apache-maven-3.0.5\bin;C:\Program Files (x86)\Common Files\NetSarang;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Common Files\Ulead Systems\MPEG;C:\Program Files\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;C:\Program Files (x86)\Intel\Services\IPT\;C:\Program Files (x86)\Common Files\Lenovo;C:\Program Files\TortoiseSVN\bin;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Program Files (x86)\VisualSVN\bin;C:\Program Files (x86)\QuickTime\QTSystem\;.
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=C:\Users\cstor\AppData\Local\Temp\
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:os.name=Windows 7
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:os.version=6.1
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:user.name=cstor
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:user.home=C:\Users\cstor
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Client environment:user.dir=C:\Users\cstor\workspace\wasp-test
13/08/05 11:20:46 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=192.168.226.100:2181 sessionTimeout=180000 watcher=fclient:
13/08/05 11:20:46 INFO zookeeper.RecoverableZooKeeper: The identifier of this process is 10528@cstor
13/08/05 11:20:46 INFO zookeeper.ClientCnxn: Opening socket connection to server master/192.168.226.100:2181. Will not attempt to authenticate using SASL (unknown error)
13/08/05 11:20:46 INFO zookeeper.ClientCnxn: Socket connection established to master/192.168.226.100:2181, initiating session
13/08/05 11:20:46 INFO zookeeper.ClientCnxn: Session establishment complete on server master/192.168.226.100:2181, sessionid = 0x1404c63e0e5002d, negotiated timeout = 180000
13/08/05 11:20:47 INFO ipc.NettyTransceiver: Successfully connected to bookie: slave1/192.168.226.101:50501
13/08/05 11:20:47 ERROR result.ResultRemote: FClinet execute sql error
com.alibaba.wasp.TableNotDisabledException: demo
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:95)
    at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:79)
    at com.alibaba.wasp.ipc.NettyTransceiver.processResponse(NettyTransceiver.java:536)
    at com.alibaba.wasp.ipc.NettyTransceiver.call(NettyTransceiver.java:496)
    at com.alibaba.wasp.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:162)
    at $Proxy4.execute(Unknown Source)
    at com.alibaba.wasp.client.FClientCallable.call(FClientCallable.java:91)
    at com.alibaba.wasp.client.FClientCallable.call(FClientCallable.java:34)
    at com.alibaba.wasp.client.ServerCallable.withRetries(ServerCallable.java:150)
    at com.alibaba.wasp.client.FClient.execute(FClient.java:104)
    at com.alibaba.wasp.client.FClient.execute(FClient.java:128)
    at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:233)
    at com.alibaba.wasp.jdbc.result.ResultRemote.<init>(ResultRemote.java:89)
    at com.alibaba.wasp.jdbc.result.ResultRemote.<init>(ResultRemote.java:95)
    at com.alibaba.wasp.jdbc.command.CommandRemote.executeUpdate(CommandRemote.java:153)
    at com.alibaba.wasp.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:723)
    at com.alibaba.wasp.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:120)
    at com.Test.main(Test.java:37)
Caused by: org.apache.hadoop.ipc.RemoteException: demo
    at com.alibaba.wasp.ipc.NettyTransceiver.processResponse(NettyTransceiver.java:533)
    ... 15 more
Exception in thread "main" java.lang.RuntimeException: com.alibaba.wasp.TableNotDisabledException: demo
    at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:243)
    at com.alibaba.wasp.jdbc.result.ResultRemote.<init>(ResultRemote.java:89)
    at com.alibaba.wasp.jdbc.result.ResultRemote.<init>(ResultRemote.java:95)
    at com.alibaba.wasp.jdbc.command.CommandRemote.executeUpdate(CommandRemote.java:153)
    at com.alibaba.wasp.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:723)
    at com.alibaba.wasp.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:120)
    at com.Test.main(Test.java:37)
Caused by: com.alibaba.wasp.TableNotDisabledException: demo
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:95)
    at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:79)
    at com.alibaba.wasp.ipc.NettyTransceiver.processResponse(NettyTransceiver.java:536)
    at com.alibaba.wasp.ipc.NettyTransceiver.call(NettyTransceiver.java:496)
    at com.alibaba.wasp.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:162)
    at $Proxy4.execute(Unknown Source)
    at com.alibaba.wasp.client.FClientCallable.call(FClientCallable.java:91)
    at com.alibaba.wasp.client.FClientCallable.call(FClientCallable.java:34)
    at com.alibaba.wasp.client.ServerCallable.withRetries(ServerCallable.java:150)
    at com.alibaba.wasp.client.FClient.execute(FClient.java:104)
    at com.alibaba.wasp.client.FClient.execute(FClient.java:128)
    at com.alibaba.wasp.jdbc.result.ResultRemote.fetchRows(ResultRemote.java:233)
    ... 6 more
Caused by: org.apache.hadoop.ipc.RemoteException: demo
    at com.alibaba.wasp.ipc.NettyTransceiver.processResponse(NettyTransceiver.java:533)
    ... 15 more

**Comment by ihadoop** [comment]
难道要手工disable 表？

**Comment by colorant** [comment]
答对了

**Comment by haosdent** [comment]
disable 'table' 后可以创建吗

**Comment by jaywong85** [comment]
DDL操作均需要disable表

**Comment by haosdent** [comment]
…...这个得更新到wiki中才行。。。。  

## 

Best Regards,
Haosong Huang
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ihadoop** [comment]
是要disable这些所有的分区表？

2013-08-05

13574798

发件人：jaywong notifications@github.com
发送时间：2013-08-05 11:30
主题：Re: [wasp] 创建索引失败 (#14)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

DDL操作均需要disable表

**Comment by jaywong85** [comment]
可以理解为所有的分区表。

**Comment by ihadoop** [comment]
13/08/05 12:14:44 INFO jdbc.JdbcConnection: Connection conn = DriverManager.getConnection("jdbc:wasp:", "", "");
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.5-1392090, built on 09/30/2012 17:52 GMT
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:host.name=cstor
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:java.version=1.7.0_02
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:java.home=C:\Program Files\Java\jre7
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:java.class.path=C:\Users\cstor\workspace\wasp-test\bin;C:\Users\cstor\workspace\wasp-test\lib\activation-1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\aopalliance-1.0.jar;C:\Users\cstor\workspace\wasp-test\lib\asm-3.1.jar;C:\Users\cstor\workspace\wasp-test\lib\avro-1.5.3.jar;C:\Users\cstor\workspace\wasp-test\lib\avro-ipc-1.5.3.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-beanutils-1.7.0.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-beanutils-core-1.8.0.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-cli-1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-codec-1.7.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-collections-3.2.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-configuration-1.6.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-digester-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-el-1.0.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-httpclient-3.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-io-2.4.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-lang-2.6.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-logging-1.1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-math-2.1.jar;C:\Users\cstor\workspace\wasp-test\lib\commons-net-1.4.1.jar;C:\Users\cstor\workspace\wasp-test\lib\core-3.1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\druid-0.2.9.jar;C:\Users\cstor\workspace\wasp-test\lib\ftplet-api-1.0.0.jar;C:\Users\cstor\workspace\wasp-test\lib\ftpserver-core-1.0.0.jar;C:\Users\cstor\workspace\wasp-test\lib\ftpserver-deprecated-1.0.0-M2.jar;C:\Users\cstor\workspace\wasp-test\lib\guava-12.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\hadoop-core-1.0.3.jar;C:\Users\cstor\workspace\wasp-test\lib\hadoop-test-1.0.3.jar;C:\Users\cstor\workspace\wasp-test\lib\hamcrest-core-1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\hbase-0.94.1-tests.jar;C:\Users\cstor\workspace\wasp-test\lib\hbase-0.94.1.jar;C:\Users\cstor\workspace\wasp-test\lib\high-scale-lib-1.1.1.jar;C:\Users\cstor\workspace\wasp-test\lib\hsqldb-1.8.0.10.jar;C:\Users\cstor\workspace\wasp-test\lib\htrace-1.49.jar;C:\Users\cstor\workspace\wasp-test\lib\httpclient-4.1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\httpcore-4.1.3.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-core-asl-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-jaxrs-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-mapper-asl-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jackson-xc-1.8.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jamon-runtime-2.3.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jasper-compiler-5.5.23.jar;C:\Users\cstor\workspace\wasp-test\lib\jasper-runtime-5.5.23.jar;C:\Users\cstor\workspace\wasp-test\lib\jaxb-api-2.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jaxb-impl-2.2.3-1.jar;C:\Users\cstor\workspace\wasp-test\lib\jersey-core-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jersey-json-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jersey-server-1.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jets3t-0.7.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jettison-1.3.1.jar;C:\Users\cstor\workspace\wasp-test\lib\jetty-6.1.26.jar;C:\Users\cstor\workspace\wasp-test\lib\jetty-util-6.1.26.jar;C:\Users\cstor\workspace\wasp-test\lib\jruby-complete-1.6.8.jar;C:\Users\cstor\workspace\wasp-test\lib\jsp-2.1-6.1.14.jar;C:\Users\cstor\workspace\wasp-test\lib\jsp-api-2.1-6.1.14.jar;C:\Users\cstor\workspace\wasp-test\lib\jsr305-1.3.9.jar;C:\Users\cstor\workspace\wasp-test\lib\junit-4.10.jar;C:\Users\cstor\workspace\wasp-test\lib\kfs-0.3.jar;C:\Users\cstor\workspace\wasp-test\lib\libthrift-0.8.0.jar;C:\Users\cstor\workspace\wasp-test\lib\log4j-1.2.17.jar;C:\Users\cstor\workspace\wasp-test\lib\metrics-core-2.1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\mina-core-2.0.0-M5.jar;C:\Users\cstor\workspace\wasp-test\lib\mockito-all-1.9.0.jar;C:\Users\cstor\workspace\wasp-test\lib\netty-3.2.4.Final.jar;C:\Users\cstor\workspace\wasp-test\lib\netty-3.5.0.Final.jar;C:\Users\cstor\workspace\wasp-test\lib\oro-2.0.8.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-java-2.4.1.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-java-format-1.2.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-rpc-pro-demo-2.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-rpc-pro-duplex-2.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\protobuf-streamer-pro-1.2.3.jar;C:\Users\cstor\workspace\wasp-test\lib\servlet-api-2.5-6.1.14.jar;C:\Users\cstor\workspace\wasp-test\lib\slf4j-api-1.4.3.jar;C:\Users\cstor\workspace\wasp-test\lib\slf4j-log4j12-1.4.3.jar;C:\Users\cstor\workspace\wasp-test\lib\snappy-java-1.0.3.2.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-aop-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-asm-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-beans-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-context-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-core-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\spring-expression-3.0.5.RELEASE.jar;C:\Users\cstor\workspace\wasp-test\lib\stax-api-1.0.1.jar;C:\Users\cstor\workspace\wasp-test\lib\velocity-1.7.jar;C:\Users\cstor\workspace\wasp-test\lib\wasp-0.10.jar;C:\Users\cstor\workspace\wasp-test\lib\xmlenc-0.52.jar;C:\Users\cstor\workspace\wasp-test\lib\zookeeper-3.4.5.jar
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:java.library.path=C:\Program Files\Java\jre7\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\MinGW\bin;C:\Program Files (x86)\Git\bin;C:\tools\apache-maven-3.0.5\bin;C:\Program Files (x86)\Common Files\NetSarang;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Common Files\Ulead Systems\MPEG;C:\Program Files\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;C:\Program Files (x86)\Intel\Services\IPT\;C:\Program Files (x86)\Common Files\Lenovo;C:\Program Files\TortoiseSVN\bin;C:\Program Files\MySQL\MySQL Server 5.5\bin;C:\Program Files (x86)\VisualSVN\bin;C:\Program Files (x86)\QuickTime\QTSystem\;.
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=C:\Users\cstor\AppData\Local\Temp\
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:os.name=Windows 7
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:os.version=6.1
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:user.name=cstor
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:user.home=C:\Users\cstor
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Client environment:user.dir=C:\Users\cstor\workspace\wasp-test
13/08/05 12:14:44 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=192.168.226.100:2181 sessionTimeout=180000 watcher=fclient:
13/08/05 12:14:44 INFO zookeeper.RecoverableZooKeeper: The identifier of this process is 9412@cstor
13/08/05 12:14:44 INFO zookeeper.ClientCnxn: Opening socket connection to server master/192.168.226.100:2181. Will not attempt to authenticate using SASL (unknown error)
13/08/05 12:14:44 INFO zookeeper.ClientCnxn: Socket connection established to master/192.168.226.100:2181, initiating session
13/08/05 12:14:44 INFO zookeeper.ClientCnxn: Session establishment complete on server master/192.168.226.100:2181, sessionid = 0x1404c63e0e50076, negotiated timeout = 180000
13/08/05 12:14:44 ERROR jdbc.JdbcPreparedStatement: exception
com.alibaba.wasp.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-1]
 at com.alibaba.wasp.jdbc.JdbcException.getJdbcSQLException(JdbcException.java:111)
 at com.alibaba.wasp.jdbc.JdbcException.get(JdbcException.java:93)
 at com.alibaba.wasp.jdbc.JdbcException.getInvalidValueException(JdbcException.java:71)
 at com.alibaba.wasp.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1282)
 at com.alibaba.wasp.jdbc.JdbcPreparedStatement.setLong(JdbcPreparedStatement.java:571)
 at com.Test.main(Test.java:46)
Exception in thread "main" com.alibaba.wasp.jdbc.JdbcSQLException: Invalid value "1" for parameter "parameterIndex" [90008-1]
 at com.alibaba.wasp.jdbc.JdbcException.getJdbcSQLException(JdbcException.java:111)
 at com.alibaba.wasp.jdbc.JdbcException.get(JdbcException.java:93)
 at com.alibaba.wasp.jdbc.JdbcException.getInvalidValueException(JdbcException.java:71)
 at com.alibaba.wasp.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1282)
 at com.alibaba.wasp.jdbc.JdbcPreparedStatement.setLong(JdbcPreparedStatement.java:571)
 at com.Test.main(Test.java:46)

插入数据报错？

PreparedStatement ps= conn.prepareStatement("insert into demo (user_id,name,age,sex) values (?,?,?,?)");

  for(int i=1;i<=1000000;i++)
  {
   ps.setLong(1, i);
   ps.setString(2, "test"+i);
   ps.setInt(3, i);
   ps.setString(4, i%2==0?"男":"女");
   ps.executeUpdate();
   conn.commit();

   ps.clearParameters();
   System.out.println(i);
  }
2013-08-05

13574798

发件人：jaywong notifications@github.com
发送时间：2013-08-05 11:38
主题：Re: [wasp] 创建索引失败 (#14)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

可以理解为所有的分区表。

**Comment by jaywong85** [comment]
用statement。别用ps

**Comment by ihadoop** [comment]
关于预分区，例子是：
CREATE TABLE user {REQUIRED INT64 user_id;
                      REQUIRED STRING name; } //以预分区的形式建表
                      PRIMARY KEY(user_id), 
                      ENTITY GROUP ROOT,
                      ENTITY GROUP KEY(user_id),
                      PARTITION BY RANGE('aaa', 'zzz', 10);

那么这个'aaa','zzz'是name字段的？

2013-08-05

13574798

发件人：jaywong notifications@github.com
发送时间：2013-08-05 12:31
主题：Re: [wasp] 创建索引失败 (#14)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

用statement。别用ps

**Comment by jaywong85** [comment]
是entityGroup key 的字段
