### ISSUE TITLE
在做范围查询时，大于查询结果为空

### ISSUE THREAD

**Issue by edmund2004** [alibaba/wasp#18]
query "select \*  from userInfo where AGE>23"，结果查询不到，但是确实是有的

**Comment by ihadoop** [comment]
有AGE的索引吗？或者AGE是索引的最后一个字段吗

2013-08-23

13574798

发件人：edmund2004 notifications@github.com
发送时间：2013-08-23 10:58
主题：[wasp] 在做范围查询时，大于查询结果为空 (#18)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送：

query "select \* from userInfo where AGE>23"，结果查询不到，但是确实是有的

**Comment by edmund2004** [comment]
是的有索引，小于是可以的，但是大于查询结果就为空，还有是不是不能支持子查询

**Comment by ihadoop** [comment]
子查询应该是不支持

2013-08-23

13574798

发件人：edmund2004 notifications@github.com
发送时间：2013-08-23 11:03
主题：Re: [wasp] 在做范围查询时，大于查询结果为空 (#18)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

是的有索引，小于是可以的，但是大于查询结果就为空，还有是不是不能支持子查询

**Comment by edmund2004** [comment]
哦，但是大于这种情况，应该是有点问题的

**Comment by edmund2004** [comment]
还有一个问题，我看到介绍说是可以支持主键的join，但是现在还不支持吗

**Comment by ihadoop** [comment]
那是未来计划
2013-08-23

13574798

发件人：edmund2004 notifications@github.com
发送时间：2013-08-23 11:24
主题：Re: [wasp] 在做范围查询时，大于查询结果为空 (#18)
收件人："alibaba/wasp"wasp@noreply.github.com
抄送："ihadoop"13574798@qq.com

还有一个问题，我看到介绍说是可以支持主键的join，但是现在还不支持吗

**Comment by edmund2004** [comment]
问一下，wasp以后会不会支持rollback（）呢

------------------ 原始邮件 ------------------
发件人: "ihadoop"notifications@github.com;
发送时间: 2013年8月23日(星期五) 中午11:25
收件人: "alibaba/wasp"wasp@noreply.github.com; 
抄送: "DNA"995076163@qq.com; 
主题: Re: [wasp] 在做范围查询时，大于查询结果为空 (#18)

 那是未来计划 
 2013-08-23 

 13574798 

 发件人：edmund2004 notifications@github.com 
 发送时间：2013-08-23 11:24 
 主题：Re: [wasp] 在做范围查询时，大于查询结果为空 (#18) 
 收件人："alibaba/wasp"wasp@noreply.github.com 
 抄送："ihadoop"13574798@qq.com 

 还有一个问题，我看到介绍说是可以支持主键的join，但是现在还不支持吗

**Comment by jaywong85** [comment]
[Issue-18]: condition with only one field, than greater than can't query any results has been fixed;

thanks for report

**Comment by alexanderdai** [comment]
@edmund2004 don't support rollback,it is unuseful in current case
