### ISSUE TITLE
Wiki的文档有问题 ？

### ISSUE THREAD

**Issue by jackcptdev** [alibaba/wasp#19]
按https://github.com/alibaba/wasp/wiki/DDL%E6%93%8D%E4%BD%9C     这里的文档操作，第一个create table user的例子显示解析错误，然后shell就退出了。

wasp(main):001:0> CREATE TABLE user {REQUIRED INT64 user_id; REQUIRED STRING name;} PRIMARY KEY(user_id), ENTITY GROUP ROOT，ENTITY GROUP KEY(user_id);
SyntaxError: (wasp):1: syntax error, unexpected tCONSTANT

CREATE TABLE user {REQUIRED INT64 user_id; REQUIRED STRING name;} PRIMARY KEY(user_id), ENTITY GROUP ROOT
                                                                        ^

Error: Your application used more stack memory than the default safety cap.
Specify -J-Xss####k to increase it (#### = cap size in KB).
Specify -w for full StackOverflowError stack trace

**Comment by jackcptdev** [comment]
my bad.......没看到要是要这样写的sql "create ...."

**Comment by haosdent** [comment]
在shell中执行sql语句需要加sql 或者 query的前缀~
