### ISSUE TITLE
现在最新版本的wasp支持多个范围条件的查询吗？

### ISSUE THREAD

**Issue by yanyanqin** [alibaba/wasp#20]
在《海量数据分布式数据库的探索》资料中看到，wasp的二级索引描述中有一项：受限的的范围条件(where条件中同时最多支 持一个范围条件)，我想知道最新版本的wasp最多支持几个范围条件的查询？
如果当前版本不支持多个范围条件的查询，那么在wasp的roadmap中对于这方面的计划是什么？
另外，当前wasp是一个实验室版本还是达到产品化要求的版本？

以上，这些决定了我们要不要选择wasp作为我们的技术解决方案。

谢谢！

**Comment by jaywong85** [comment]
新版本不限制使用条件范围个数。但是也有一些限制。
举个例子，你建的索引是C1,C2,C3.  但是你查询的时候可以在c1,c2,c3条件都用上的基础上，再加任意多个条件，这些条件都是可以用范围查询的。但是c1,c2,c3本身还是只能c3是范围条件的。
