### ISSUE TITLE
the wiki page is out of date.

### ISSUE THREAD

**Issue by colorant** [alibaba/wasp#5]
Hi

I can see that the wiki page is some how out of date and not sync with current code?

e.g. to do a select \* from user where user_id=1

you won't be able to use
  sql "select \* from user where user_id=1"
you must use 
  query "select \* from user where user_id=1"

And btw. why need to use sql/query etc? if must, why two keywords....

And some DDL need to be run with sql, say create table, while some DDL could not , and need to be run directly in shell cmd interface, say disalbe/drop table etc.

And, then the cmd line help is a little bit too simple ? say select won't support a query without "where" clause. etc.

It seems to be a little bit of annoying when I follow the wiki and it don't give the right result, and I had to figure out what is the right thing to do by myself with a lot of guess and try...

A complete grammer is needed if it is really intended to be try out by other peoples I guess.

**Comment by jaywong85** [comment]
wiki edited.thx.

wasp sql paser is not at client side. so the client don't know it is a DQL or not. so we have two keywords.
