### ISSUE TITLE
fserver web ui port 50030?

### ISSUE THREAD

**Issue by colorant** [alibaba/wasp#7]
by wiki, Wasp fserver基于WEB的UI服务端口默认为50030 

while, in the config file, wasp-default.xml, the wasp.fserver.info.port is set to 5051

are these the same thing? or some of them should be fmaster's web ui port? any way I am confused.

And , then, 50030 is map reduce jobtracker's default port, shouldn't we pick another port number to avoid conflict?

finally, what is the web page looks like ?

in my set up. no mater 5051 or 60080 port, the page show only :

Directory: /

WEB-INF/    4096 bytes  Jul 29, 2013 9:04:33 AM

nothing else. though I do have created table through wasp shell.

**Comment by jaywong85** [comment]
start your fserver.then
http://fserver_host:50030/fs-status

**Comment by colorant** [comment]
seems it is 

http://fserver_host:5051/fs-status and http://fserver_master:60080/master-status

Guess you have update the code to not use 50030 while wiki not update yet.

**Comment by jaywong85** [comment]
60080 is mater webUI port. fserver DEFAULT wetUI is 50030. and U can set it what U want :)
